import { StyleSheet } from "react-native";
import { Colors } from "./Colors";


export const styles = StyleSheet.create({
    titleContainer: {
      height: "75%",
      width:"100%",
      justifyContent: 'center',
      alignItems: "center",
      borderBottomEndRadius: 200,
      borderBottomStartRadius: 200,
      backgroundColor: Colors.verdeClaro
    },
    container: {
      flex:1,
      backgroundColor: "white",
      width:"100%",
      alignItems: 'center',
      justifyContent: 'center',
    },
    contInput: {
      width: "100%",  
      alignItems: 'center',
      marginVertical: 10,
    },
    textInput: {
      padding:10, 
      fontSize: 20,
      borderRadius: 10,
      borderColor: "grey",
      borderWidth: 2,
      width: "90%",
    },
    logo: {
      height: "60%",
    },
    btnPersonalizado: {
      borderColor: Colors.verdeClaro,
      borderWidth: 1,
      borderRadius: 15,
      alignItems:"center",
      margin: 15,
      padding: 15,
    },
    roundBox: {
      width:"90%",
      borderColor: "grey",
      borderWidth: 1,
      borderRadius: 20,
      margin: 5,
      marginTop: 12,
      padding: 5,
    },
    btnListItem: {
      width:"95%",
      flex:1,
      flexDirection:"row",
      borderColor: "grey",
      borderWidth: 1,
      borderRadius: 20,
      margin: 5,
      marginVertical: 7,
      padding: 5,
    },
    input: {
      backgroundColor: 'white',
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderWidth: 1,
      borderColor: 'grey',
      marginBottom: 20,
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 3,
    },
    header: {
      position: "relative",
      zIndex: 10,
      marginTop: 30, 
      marginHorizontal: 10,
      paddingHorizontal: 30,
      alignItems: 'center', 
      justifyContent:"space-between", 
      width:"100%", 
      flexDirection: "row", 
    },
    card: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: "#eee",
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderRadius: 10,
      marginBottom: 10,
      shadowColor: 'black',
      shadowOpacity: 0.2,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3, // Sombra para Android
    },
  });